name: Claude Code

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, edited]
  pull_request_review_comment:
    types: [created, edited]

jobs:
  claude:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: |
      (github.event.issue.body && contains(github.event.issue.body, '@claude')) ||
      (github.event.comment.body && contains(github.event.comment.body, '@claude')) ||
      (github.event.pull_request.body && contains(github.event.pull_request.body, '@claude')) ||
      (github.event.review.body && contains(github.event.review.body, '@claude'))
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        timeout-minutes: 2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Claude Code
        uses: anthropics/claude-code-action@beta
        timeout-minutes: 3
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_SECRET }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Claude Code
        timeout-minutes: 5
        run: |
          echo "Claude Code is processing the request..."