name: Claude Code

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, edited]
  pull_request_review_comment:
    types: [created, edited]

permissions:
  contents: read
  pull-requests: read
  issues: read
  id-token: write

jobs:
  claude:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: |
      (github.event.issue.body && contains(github.event.issue.body, '@claude')) ||
      (github.event.comment.body && contains(github.event.comment.body, '@claude')) ||
      (github.event.pull_request.body && contains(github.event.pull_request.body, '@claude')) ||
      (github.event.review.body && contains(github.event.review.body, '@claude'))
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Claude Code Review
        uses: anthropics/claude-code-action@beta
        timeout-minutes: 8
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_SECRET }}
          timeout_minutes: 10